#!/usr/bin/env python3
"""Generate the gzip-compressed embedded SPA JavaScript header."""
from pathlib import Path
import gzip

if "Import" in globals():
    Import("env")
    root = Path(env.subst("$PROJECT_DIR")).resolve()
else:
    root = Path(__file__).resolve().parents[1]

payload = (root / "src/app_spa.js").read_bytes()
compressed = gzip.compress(payload, compresslevel=9, mtime=0)
lines = [
    "#pragma once",
    "",
    "#include <Arduino.h>",
    "",
    "// Generated by scripts/generate_spa_gzip.py; do not edit manually.",
    "static const uint8_t appJsSpaGzip[] PROGMEM = {",
]
for offset in range(0, len(compressed), 16):
    chunk = compressed[offset:offset + 16]
    lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
lines.extend(["};", "", "static constexpr size_t appJsSpaGzipLength = sizeof(appJsSpaGzip);", ""])
output = root / "src/app_js_spa_gz.h"
generated = "\n".join(lines)
if not output.exists() or output.read_text(encoding="utf-8") != generated:
    output.write_text(generated, encoding="utf-8")
    action = "Updated"
else:
    action = "Verified"
print(f"{action} {output.name}: {len(payload)} bytes -> {len(compressed)} bytes")
